print("------------------ Starts with str ----------------------------")
msg = "Roll a dice!"
print(msg.capitalize())
print(msg.upper())
print(msg.lower())
print(msg.title())
print(msg.swapcase())
print(msg.replace("dice", "coin"))
print(msg.split(" "))
print(msg.strip())
print(msg.lstrip())
print(msg.rstrip())
print(msg.startswith("Roll"))
print(msg.endswith("!"))
print(msg.find("a"))
print(msg.rfind("a"))
print(msg.index("a"))
print(msg.rindex("a"))
print(msg.count("a"))
print(msg.isalnum())
print(msg.isalpha())
print(msg.isdecimal())
print(msg.isdigit())
print(msg.isidentifier())
print(msg.islower())
print(msg.isupper())
print(msg.isspace())
print(msg.isnumeric())
print(msg.isprintable())
print(msg.zfill(20))
print(msg.center(20))
print(msg.ljust(20))
print(msg.rjust(20))    
print("------------------ Now Python List ----------------------------")
names = ['Alice', 'Bob', 'Charlie']
print(names)
print(names[0])
print(names[1])
print(names[2])
print(names[-1])
print(names[-2])
print(names[-3])
print(names[1:3])
print(names[1:])
print(names[:2])
print(names[::2])
print(names[::-1])
print(names[1:3])

# 문자열 출력
print("----------------- Hello Python String -------------------------")
print \
        ('Hello, I\'m ', 18 , 'years old.' , 20 - 18,'years left to 20.')

